apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: tyk-crd-migration-operator-mask
spec:
  name: "Tyk CRD Migration Operator Mask"
  active: true
  use_keyless: true
  proxy:
    target_url: http://httpbin.org
    listen_path: /operator-mask
    strip_listen_path: true
  version_data:
    default_version: Default
    not_versioned: true
    versions:
      Default:
        name: Default
        use_extended_paths: true
        paths:
          black_list: []
          ignored: []
          white_list: []
        extended_paths:
          ignored:
            - ignore_case: false
              method_actions:
                GET:
                  action: "reply"
                  code: 200
                  data: '{"x-agent": "tyk-crd-migration", "x-action": "mask", "message": "Masking Operator Functionality"}'
                  headers: {"Content-Type": "application/json"}
                POST:
                  action: "reply"
                  code: 200
                  data: '{"x-agent": "tyk-crd-migration", "x-action": "mask", "message": "Masking Operator Functionality"}'
                  headers: {"Content-Type": "application/json"}
                DELETE:
                  action: "reply"
                  code: 200
                  data: '{"x-agent": "tyk-crd-migration", "x-action": "mask", "message": "Masking Operator Functionality"}'
                  headers: {"Content-Type": "application/json"}
                PUT:
                  action: "reply"
                  code: 200
                  data: '{"x-agent": "tyk-crd-migration", "x-action": "mask", "message": "Masking Operator Functionality"}'
                  headers: {"Content-Type": "application/json"}
              path: /*